### ISSUE TITLE
RPC implementation

### ISSUE THREAD

**Issue by tosbaha** [AfterShip/bsw#4]
Hi,
Is it possible to add RPC implementation to bsw? Since sometimes we want to use beanstalkd to communicate between Producer and Consumer. So Producer will put the job and also create a consumer on a reply tube. When Consumer finishes the job, it will put result to reply tube.

**Comment by eric4545** [comment]
Hi @tosbaha,
Currently we are not active development on bsw, but PR is welcome.
Btw are you requesting feature similar to [nats-req-rep](https://nats.io/documentation/concepts/nats-req-rep/)?

**Comment by tosbaha** [comment]
Yes it is very similar to `nats-req-rep` I have come up with something that works but I would love to hear your opinions. I just made a quick example with RPC and pushed to https://github.com/tosbaha/bsw PS:There was a tiny typo in the README I also fixed that.
